# workflow/Snakefile
# Entrypoint
configfile: "config/config.yaml"

def get_pam_fasta(wildcards):
    if config.get("test_mode", False):
        return "results/03_pam_discovery/ISO1.masked.euchromatic.PAMs.10pct.fa"
    return "results/03_pam_discovery/ISO1.masked.euchromatic.PAMs.fa"

rule all:
    input:
        # The main data output
        #"results/07_summary/conserved_pams.csv",
        "results/08_figures/multi_tolerance_venn.png",
        "results/08_figures/cfd_shift.png"
        #"results/07_summary/pam_orthology_summary.csv",
        # The visualization output (this triggers the plotter, which triggers the mapper)
        #"results/08_figures"

# Import the modules
include: "rules/preliminaries.smk"
include: "rules/mapping.smk"
include: "rules/scoring.smk"
#include: "rules/tmp.smk"